# Generated by Django 6.0.2 on 2026-02-28 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@iluffy.com", max_length=254),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.TextField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("discord_url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Info",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total annual price (shown as per-month equivalent on the card)",
                        max_digits=8,
                    ),
                ),
                (
                    "monthly_original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strike-through original monthly price (leave blank if none)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "annual_original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Strike-through original annual price (leave blank if none)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_popular", models.BooleanField(default=False)),
                ("cta_label", models.CharField(default="Get Started", max_length=60)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=150)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("quote", models.TextField()),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True, help_text="URL to avatar image (optional)"
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="1-5 star rating"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("tooltip", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="main.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
