# Generated by Django 6.0.2 on 2026-02-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_base_url",
                    models.URLField(
                        default="https://app.iluffy.in",
                        help_text="Base URL of the main application (no trailing slash)",
                    ),
                ),
                (
                    "register_path",
                    models.CharField(default="/register", max_length=100),
                ),
                ("login_path", models.CharField(default="/login", max_length=100)),
                ("billing_path", models.CharField(default="/billing", max_length=100)),
                (
                    "sample_report_url",
                    models.CharField(
                        default="#",
                        help_text="URL for 'View Sample Report' button (use # as placeholder)",
                        max_length=300,
                    ),
                ),
                ("nav_login_label", models.CharField(default="Log in", max_length=60)),
                (
                    "nav_cta_label",
                    models.CharField(default="Analyze Now", max_length=60),
                ),
                (
                    "hero_cta_label",
                    models.CharField(default="Start Analysis", max_length=60),
                ),
                (
                    "hero_secondary_label",
                    models.CharField(default="Sample Report", max_length=60),
                ),
                (
                    "cta_primary_label",
                    models.CharField(default="Get Started Free", max_length=60),
                ),
                (
                    "cta_secondary_label",
                    models.CharField(default="View Pricing", max_length=60),
                ),
            ],
            options={
                "verbose_name": "Site Config",
                "verbose_name_plural": "Site Config",
            },
        ),
        migrations.AddField(
            model_name="plan",
            name="cta_url_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("billing", "Billing"),
                    ("login", "Login"),
                ],
                default="register",
                help_text="Which app URL this plan's button links to",
                max_length=20,
            ),
        ),
    ]
