# Generated by Django 6.0.2 on 2026-02-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_siteconfig_plan_cta_url_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="annual_original_price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="annual_price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="monthly_original_price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="monthly_price",
        ),
        migrations.AddField(
            model_name="plan",
            name="credits_per_month",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of credits included per month"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of features. Each item: {"name": "Feature name", "included": true/false}. Example: [{"name": "ATS score breakdown", "included": true}, {"name": "Priority AI processing", "included": false}]',
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="mrp_annual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Original (MRP) total annual price (mrp_monthly × 12)",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="mrp_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Original (MRP) monthly price — shown as strike-through if different from discounted",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_annual",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discounted total annual price actually charged",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Discounted monthly price actually charged",
                max_digits=8,
            ),
        ),
        migrations.DeleteModel(
            name="PlanFeature",
        ),
    ]
